### ISSUE TITLE
Ende einer Ära

### ISSUE THREAD

**Issue by gruselhaus** [GruselhausOrganization/api#240]
@juliakonstanz ich habe mich eben mit @juliakonstanz beraten. Das Projekt hier war eig nur als Krücke vorhergesehen (also als Proxy für das Monitoring) und hat nun ausgedient. Wir haben uns dazu entschieden, das Proxy Feature herauszunehmen und in einer neuer Sprache (Dino) umzusetzen. Das Projekt hier hat uns 1 Jahr lang gut gedient und tatsächlich 4 Milliarden Anfragen verarbeitet. Ich werde api.gruselhaus.com gleich abschalten und dieses Repository archivieren.

Danke für deine Mühen, du wirst uns bestimmt beim neuen Projekt wieder sehr hilfreich sein ❤️

**Comment by emilyrattinger** [comment]
Vielen Dank @juliakonstanz ❤️

**Comment by juliakonstanz** [comment]
Guten Morgen ihr beiden ☀️,

vielen vielen Dank!

Natürlich bin ich beim neuen Projekt wieder dabei 😇

Lasst uns später doch mal telefonieren....

Eure Julia
