### ISSUE TITLE
[API-86]

### ISSUE THREAD

**Issue by gruselhaus** [GruselhausOrganization/api#28]
@juliakonstanz Kannst du dir bitte mal Ticket API-86 anschauen? Ich bekomme gerade diverse Mails und Nachrichten von Usern, wo scheinbar ein Authentifizierungsproblem auftritt. Ich vermute, dass das Problem in der Firebase DB liegt.

**Comment by gruselhaus** [comment]
BTW: Ich fände es gut, wenn wir uns von Google trennen und die DB mit in die GSI DB migrieren. Kannst Du mir da bitte mal einen Zeitansatz zukommen lassen? Aktuell bedienen wir 2151 User.

**Comment by juliakonstanz** [comment]
> @juliakonstanz Kannst du dir bitte mal Ticket API-86 anschauen? Ich bekomme gerade diverse Mails und Nachrichten von Usern, wo scheinbar ein Authentifizierungsproblem auftritt. Ich vermute, dass das Problem in der Firebase DB liegt.

@gruselhaus Ich habe gerade mal einen Neutstart vom Container durchgeführt. Das Problem lag wohl im Cache. Soll ich gerade mal einen Rundruf ausführen?

@GruselhausBot close [API-86]

**Comment by juliakonstanz** [comment]
> BTW: Ich fände es gut, wenn wir uns von Google trennen und die DB mit in die GSI DB migrieren. Kannst Du mir da bitte mal einen Zeitansatz zukommen lassen? Aktuell bedienen wir 2151 User.

Ich denke, dass ich die Anpassungen an der API in ~30-40 min schaffen werde. Plus Migration ~70 min.

**Comment by gruselhaus** [comment]
> > BTW: Ich fände es gut, wenn wir uns von Google trennen und die DB mit in die GSI DB migrieren. Kannst Du mir da bitte mal einen Zeitansatz zukommen lassen? Aktuell bedienen wir 2151 User.
> 
> Ich denke, dass ich die Anpassungen an der API in ~30-40 min schaffen werde. Plus Migration ~70 min.

Dann bitte so umsetzen 😇
